const qs=s=>document.querySelector(s),qsa=s=>document.querySelectorAll(s);
const groceryFallback='https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80';
const imgErr="this.onerror=null;this.src='"+groceryFallback+"'";
const CATEGORIES=['All','Fruits','Vegetables','Dairy','Bakery','Snacks','Beverages','Household','Personal Care'];
const products=[
{id:1,name:'Fresh Apple Pack',category:'Fruits',price:149,image:'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',description:'Crisp imported apples, 1 kg pack.',rating:4.7,stock:42,featured:true,nutrition:{cal:52,protein:0.3,sugar:10},badge:'Best Seller'},
{id:2,name:'Banana Robusta',category:'Fruits',price:55,image:'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',description:'Naturally sweet bananas, 1 dozen.',rating:4.5,stock:60,featured:true,nutrition:{cal:89,protein:1.1,sugar:12},badge:'Fresh'},
{id:3,name:'Orange Valencia',category:'Fruits',price:120,image:'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?auto=format&fit=crop&w=600&q=80',description:'Juicy vitamin-rich oranges.',rating:4.4,stock:34,featured:false,nutrition:{cal:47,protein:0.9,sugar:9},badge:'Juicy'},
{id:4,name:'Strawberry Box',category:'Fruits',price:199,image:'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',description:'Premium strawberries for desserts.',rating:4.6,stock:18,featured:true,nutrition:{cal:33,protein:0.7,sugar:4.9},badge:'Premium'},
{id:5,name:'Mango Alphonso',category:'Fruits',price:299,image:'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80',description:'Seasonal sweet mangoes.',rating:4.8,stock:20,featured:true,nutrition:{cal:60,protein:0.8,sugar:14},badge:'Seasonal'},
{id:6,name:'Green Grapes',category:'Fruits',price:95,image:'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=600&q=80',description:'Seedless green grapes.',rating:4.3,stock:25,featured:false,nutrition:{cal:69,protein:0.7,sugar:16},badge:'Seedless'},
{id:7,name:'Fresh Tomato',category:'Vegetables',price:38,image:'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=600&q=80',description:'Red farm tomatoes, 1 kg.',rating:4.4,stock:55,featured:true,nutrition:{cal:18,protein:0.9,sugar:2.6},badge:'Farm Fresh'},
{id:8,name:'Potato',category:'Vegetables',price:32,image:'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',description:'Daily-use potatoes, 1 kg.',rating:4.2,stock:80,featured:false,nutrition:{cal:77,protein:2,sugar:0.8},badge:'Value'},
{id:9,name:'Carrot',category:'Vegetables',price:48,image:'https://images.unsplash.com/photo-1445282768818-728615cc910a?auto=format&fit=crop&w=600&q=80',description:'Crunchy carrots, 500 g.',rating:4.5,stock:38,featured:true,nutrition:{cal:41,protein:0.9,sugar:4.7},badge:'Healthy'},
{id:10,name:'Broccoli',category:'Vegetables',price:145,image:'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=600&q=80',description:'Fresh green broccoli.',rating:4.6,stock:15,featured:true,nutrition:{cal:34,protein:2.8,sugar:1.7},badge:'Organic'},
{id:11,name:'Spinach Bunch',category:'Vegetables',price:35,image:'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80',description:'Leafy spinach bunch.',rating:4.3,stock:30,featured:false,nutrition:{cal:23,protein:2.9,sugar:0.4},badge:'Leafy'},
{id:12,name:'Onion',category:'Vegetables',price:42,image:'https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=600&q=80',description:'Kitchen essential onions.',rating:4.1,stock:90,featured:false,nutrition:{cal:40,protein:1.1,sugar:4.2},badge:'Essential'},
{id:13,name:'Amul Milk 1L',category:'Dairy',price:68,image:'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',description:'Fresh toned milk.',rating:4.7,stock:75,featured:true,nutrition:{cal:61,protein:3.2,sugar:5},badge:'Daily'},
{id:14,name:'Greek Yogurt',category:'Dairy',price:99,image:'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80',description:'Thick creamy yogurt.',rating:4.6,stock:28,featured:true,nutrition:{cal:59,protein:10,sugar:3.2},badge:'Protein'},
{id:15,name:'Cheddar Cheese',category:'Dairy',price:165,image:'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=600&q=80',description:'Cheese slices for snacks.',rating:4.5,stock:24,featured:false,nutrition:{cal:402,protein:25,sugar:1.3},badge:'Creamy'},
{id:16,name:'Butter Salted',category:'Dairy',price:58,image:'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&q=80',description:'Smooth salted butter.',rating:4.4,stock:36,featured:false,nutrition:{cal:717,protein:0.9,sugar:0.1},badge:'Smooth'},
{id:17,name:'Paneer Fresh',category:'Dairy',price:120,image:'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',description:'Soft paneer cubes, 200 g.',rating:4.5,stock:22,featured:true,nutrition:{cal:265,protein:18,sugar:1.2},badge:'Fresh'},
{id:18,name:'Fresh Cream',category:'Dairy',price:75,image:'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80',description:'Rich dairy cream.',rating:4.2,stock:19,featured:false,nutrition:{cal:340,protein:2.1,sugar:3},badge:'Rich'},
{id:19,name:'Whole Wheat Bread',category:'Bakery',price:45,image:'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',description:'Soft healthy bread loaf.',rating:4.5,stock:40,featured:true,nutrition:{cal:247,protein:13,sugar:5},badge:'Fresh Baked'},
{id:20,name:'Croissant Pack',category:'Bakery',price:149,image:'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',description:'Buttery croissants.',rating:4.7,stock:16,featured:true,nutrition:{cal:406,protein:8,sugar:6},badge:'Cafe Style'},
{id:21,name:'Chocolate Muffins',category:'Bakery',price:129,image:'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=600&q=80',description:'Pack of 4 muffins.',rating:4.4,stock:18,featured:false,nutrition:{cal:377,protein:5,sugar:28},badge:'Sweet'},
{id:22,name:'Cookies Jar',category:'Bakery',price:115,image:'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80',description:'Crunchy cookies.',rating:4.3,stock:33,featured:false,nutrition:{cal:488,protein:6,sugar:30},badge:'Crunchy'},
{id:23,name:'Donut Box',category:'Bakery',price:189,image:'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=600&q=80',description:'Assorted donuts.',rating:4.6,stock:14,featured:true,nutrition:{cal:452,protein:5,sugar:24},badge:'Treat'},

{id:25,name:'Potato Chips',category:'Snacks',price:35,image:'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80',description:'Masala potato chips.',rating:4.4,stock:100,featured:true,nutrition:{cal:536,protein:7,sugar:0.5},badge:'Hot Deal'},
{id:26,name:'Salted Popcorn',category:'Snacks',price:60,image:'https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?auto=format&fit=crop&w=600&q=80',description:'Cinema-style popcorn.',rating:4.3,stock:45,featured:false,nutrition:{cal:387,protein:12,sugar:0.9},badge:'Movie'},
{id:27,name:'Mixed Namkeen',category:'Snacks',price:79,image:'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?auto=format&fit=crop&w=600&q=80',description:'Spicy Indian namkeen.',rating:4.2,stock:50,featured:false,nutrition:{cal:550,protein:10,sugar:3},badge:'Spicy'},
{id:28,name:'Dark Chocolate',category:'Snacks',price:125,image:'https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&w=600&q=80',description:'Rich dark chocolate bar.',rating:4.7,stock:30,featured:true,nutrition:{cal:546,protein:4.9,sugar:24},badge:'Premium'},
{id:29,name:'Granola Bar',category:'Snacks',price:45,image:'https://images.unsplash.com/photo-1622484211148-6c04f0b81a26?auto=format&fit=crop&w=600&q=80',description:'Healthy oats bar.',rating:4.1,stock:38,featured:false,nutrition:{cal:471,protein:10,sugar:18},badge:'Fit'},
{id:30,name:'Roasted Peanuts',category:'Snacks',price:85,image:'https://images.unsplash.com/photo-1567892737950-30c4db37cd89?auto=format&fit=crop&w=600&q=80',description:'Salted roasted peanuts.',rating:4.3,stock:44,featured:false,nutrition:{cal:567,protein:26,sugar:4},badge:'Protein'},
{id:31,name:'Orange Juice',category:'Beverages',price:110,image:'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=600&q=80',description:'Fresh orange juice.',rating:4.5,stock:26,featured:true,nutrition:{cal:45,protein:0.7,sugar:8.4},badge:'Chilled'},
{id:32,name:'Cola Bottle',category:'Beverages',price:65,image:'https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=600&q=80',description:'Classic cola 1.25 L.',rating:4.3,stock:70,featured:false,nutrition:{cal:42,protein:0,sugar:10.6},badge:'Party'},
{id:33,name:'Mineral Water',category:'Beverages',price:20,image:'https://images.unsplash.com/photo-1564419320461-6870880221ad?auto=format&fit=crop&w=600&q=80',description:'Pure drinking water.',rating:4.2,stock:120,featured:false,nutrition:{cal:0,protein:0,sugar:0},badge:'Pure'},
{id:34,name:'Cold Coffee',category:'Beverages',price:85,image:'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=600&q=80',description:'Ready-to-drink cold coffee.',rating:4.4,stock:32,featured:true,nutrition:{cal:65,protein:2.1,sugar:8},badge:'Cafe'},
{id:35,name:'Green Tea Box',category:'Beverages',price:140,image:'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80',description:'Refreshing green tea bags.',rating:4.5,stock:29,featured:false,nutrition:{cal:1,protein:0,sugar:0},badge:'Wellness'},
{id:36,name:'Energy Drink',category:'Beverages',price:99,image:'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',description:'Instant energy drink.',rating:4.1,stock:37,featured:false,nutrition:{cal:45,protein:0,sugar:11},badge:'Energy'},
{id:37,name:'Laundry Detergent',category:'Household',price:245,image:'https://images.unsplash.com/photo-1624372635310-1ea33e6f1c80?auto=format&fit=crop&w=600&q=80',description:'Power-clean detergent.',rating:4.6,stock:24,featured:true,nutrition:null,badge:'Top Rated'},

{id:41,name:'Bath Soap Pack',category:'Personal Care',price:125,image:'https://images.unsplash.com/photo-1607006344380-b6775a0824a7?auto=format&fit=crop&w=600&q=80',description:'Gentle bathing soap.',rating:4.4,stock:48,featured:false,nutrition:null,badge:'Gentle'},
{id:42,name:'Shampoo Bottle',category:'Personal Care',price:195,image:'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=600&q=80',description:'Smooth hair shampoo.',rating:4.5,stock:26,featured:true,nutrition:null,badge:'Smooth'},
{id:43,name:'Toothpaste',category:'Personal Care',price:90,image:'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=600&q=80',description:'Fresh mint toothpaste.',rating:4.4,stock:58,featured:false,nutrition:null,badge:'Mint'},
{id:44,name:'Hand Sanitizer',category:'Personal Care',price:75,image:'https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=600&q=80',description:'Kills 99.9% germs.',rating:4.3,stock:46,featured:false,nutrition:null,badge:'Safe'}
];
const partners=[{name:'Rahul Sharma',phone:'+91 98765 43210',vehicle:'Electric Bike',rating:4.8,photo:'🧑‍✈️'},{name:'Priya Verma',phone:'+91 99887 77665',vehicle:'Scooter',rating:4.9,photo:'👩‍✈️'},{name:'Aman Khan',phone:'+91 91234 56789',vehicle:'Bike',rating:4.7,photo:'🏍️'},{name:'Rohit Patel',phone:'+91 90909 12345',vehicle:'E-cycle',rating:4.6,photo:'🚴'}];
const heroSlides=[['Fresh groceries delivered in minutes','Use FIRST50, SAVE100, WELCOME20 or FREESHIP in your cart.','🥦'],['Mega fruit festival','Real images, fresh stock and smart recommendations.','🍎'],['Daily essentials under one roof','Household, personal care, snacks and bakery in one demo app.','🧺']];
let user=JSON.parse(localStorage.getItem('apna_user')||'null'),otp='',authMode='create',currentCategory='All',currentSort='default',searchTerm='',heroIndex=0,spinRotation=0;
const scopedKeys={apna_cart:'cart',apna_orders:'orders',apna_wishlist:'wishlist',apna_notifications:'notifications',apna_tracking:'tracking',apna_coupon:'coupon',apna_recent:'recent',apna_wheel_coupon:'wheel_coupon',apna_spin_day:'spin_day'};
function cleanPhone(v=''){return String(v).replace(/\D/g,'').slice(-10)}
function activeUserId(){return user?cleanPhone(user.phone)||String(user.username||user.name).toLowerCase().replace(/\W+/g,'_'):'guest'}
function scopedKey(k){return scopedKeys[k]?`apna_${activeUserId()}_${scopedKeys[k]}`:k}
function readScoped(k,fb){const raw=localStorage.getItem(scopedKey(k));try{return JSON.parse(raw??fb)}catch{return JSON.parse(fb)}}
function readAccounts(){try{return JSON.parse(localStorage.getItem('apna_accounts')||'{}')}catch{return {}}}
function writeAccounts(v){localStorage.setItem('apna_accounts',JSON.stringify(v))}
function refreshState(){cart=readScoped('apna_cart','{}');orders=readScoped('apna_orders','[]');wishlist=readScoped('apna_wishlist','[]');notifications=readScoped('apna_notifications','[]');tracking=readScoped('apna_tracking','null');coupon=localStorage.getItem(scopedKey('apna_coupon'))||''}
function rerenderAll(){renderCart();renderProducts();renderOrderHistory();renderDashboard();renderRecommendations();renderUser();renderNotifications();if(tracking){showTracking(tracking)}else qs('#trackingSection')?.classList.add('hidden')}
let cart={},orders=[],wishlist=[],notifications=[],tracking=null,coupon='';refreshState();
function save(k,v){const key=scopedKey(k);if(typeof v==='string')localStorage.setItem(key,v);else localStorage.setItem(key,JSON.stringify(v))}function money(n){return '₹'+Math.max(0,Math.round(n))}function product(id){return products.find(p=>p.id==id)}function toast(msg,type='success'){const t=document.createElement('div');t.className='toast '+type;t.textContent=msg;qs('#toastContainer').appendChild(t);setTimeout(()=>t.classList.add('show'),30);setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),250)},3200)}
function addNotification(text){notifications.unshift({id:Date.now(),text,date:new Date().toISOString()});notifications=notifications.slice(0,20);save('apna_notifications',notifications);renderNotifications();}
function openModal(id){qs('#overlay').classList.add('active');qs('#'+id).classList.add('active');qs('#'+id).setAttribute('aria-hidden','false')}function closeModal(id){qs('#overlay').classList.remove('active');qs('#'+id).classList.remove('active');qs('#'+id).setAttribute('aria-hidden','true')}function closeAll(){qsa('.modal').forEach(m=>m.classList.remove('active'));qs('#overlay').classList.remove('active');qs('#cartDrawer').classList.remove('open');qs('#mobilePanel').classList.remove('open')}
function init(){qs('#categoryFilter').innerHTML=CATEGORIES.map(c=>`<option>${c}</option>`).join('');bindEvents();setAuthMode('create');renderProducts();renderCart();renderOrderHistory();renderDashboard();renderRecommendations();renderUser();renderNotifications();startHero();startFlashTimer();if(tracking){showTracking(tracking);startDeliveryTracking(tracking,false)}if(localStorage.getItem('apna_dark')==='true')document.body.classList.add('dark');qs('#themeBtn').textContent=document.body.classList.contains('dark')?'☀️':'🌙'}
function bindEvents(){qs('#brandHome').onclick=()=>scrollTo({top:0,behavior:'smooth'});qs('#shopNowBtn').onclick=()=>qs('#productsSection').scrollIntoView({behavior:'smooth'});qs('#openCartBtn').onclick=()=>{qs('#cartDrawer').classList.add('open');qs('#overlay').classList.add('active');renderCart()};qs('#closeCartBtn').onclick=closeAll;qs('#overlay').onclick=closeAll;qsa('[data-close-modal]').forEach(b=>b.onclick=()=>closeModal(b.dataset.closeModal));qs('#searchInput').oninput=e=>{searchTerm=e.target.value.trim();renderSuggestions();renderProducts()};qs('#categoryFilter').onchange=e=>{currentCategory=e.target.value;renderProducts()};qs('#sortFilter').onchange=e=>{currentSort=e.target.value;renderProducts()};qs('#clearCartBtn').onclick=()=>{cart={};save('apna_cart',cart);renderCart();renderProducts();toast('Cart cleared','warning')};qs('#applyCouponBtn').onclick=()=>applyCoupon(qs('#couponInput').value.trim().toUpperCase());qs('#checkoutOpenBtn').onclick=checkout;qs('#sendOtpBtn').onclick=loginWithOtp;qs('#verifyOtpBtn').onclick=verifyOtp;if(qs('#resendOtpBtn'))qs('#resendOtpBtn').onclick=loginWithOtp;if(qs('#createAccountTab'))qs('#createAccountTab').onclick=()=>setAuthMode('create');if(qs('#loginAccountTab'))qs('#loginAccountTab').onclick=()=>setAuthMode('login');qs('#userBtn').onclick=()=>user?showProfile():openModal('loginModal');qs('#ordersBtn').onclick=()=>{renderOrderHistory();openModal('ordersModal')};qs('#wishlistBtn').onclick=()=>{renderWishlist();openModal('wishlistModal')};qs('#notifyBtn').onclick=()=>openModal('notificationsModal');qs('#placeOrderBtn').onclick=placeOrder;qs('#spinOpenBtn').onclick=()=>openModal('spinModal');qs('#spinPromo').onclick=()=>openModal('spinModal');qs('#spinBtn').onclick=spinWheel;qs('#detectLocationBtn').onclick=detectLocation;if(qs('#mapLocateBtn'))qs('#mapLocateBtn').onclick=detectLocation;qs('#themeBtn').onclick=toggleTheme;qs('#assistantBtn').onclick=assistantSuggest;qs('#buyAgainBtn').onclick=buyAgain;qs('#menuBtn').onclick=()=>qs('#mobilePanel').classList.add('open');qs('#closeMobilePanel').onclick=()=>qs('#mobilePanel').classList.remove('open');qsa('.kit-card').forEach(k=>k.onclick=()=>addKit(k.dataset.kit));qsa('[data-panel-action]').forEach(b=>b.onclick=()=>{closeAll();({orders:()=>qs('#ordersBtn').click(),wishlist:()=>qs('#wishlistBtn').click(),notifications:()=>qs('#notifyBtn').click(),cart:()=>qs('#openCartBtn').click()})[b.dataset.panelAction]()});}
function renderProducts(){let list=products.filter(p=>(currentCategory==='All'||p.category===currentCategory)&&(p.name.toLowerCase().includes(searchTerm.toLowerCase())||p.description.toLowerCase().includes(searchTerm.toLowerCase())));if(currentSort==='priceLow')list.sort((a,b)=>a.price-b.price);if(currentSort==='priceHigh')list.sort((a,b)=>b.price-a.price);if(currentSort==='ratingHigh')list.sort((a,b)=>b.rating-a.rating);if(currentSort==='default')list.sort((a,b)=>Number(b.featured)-Number(a.featured)||b.rating-a.rating);qs('#noProducts').classList.toggle('hidden',list.length>0);qs('#productGrid').innerHTML=list.map(card).join('');}
function card(p){const q=cart[p.id]||0,stock=p.stock-q,wish=wishlist.includes(p.id);return `<article class="product-card"><span class="tag">${p.badge||'Fresh'}</span><button class="heart ${wish?'active':''}" onclick="toggleWishlist(${p.id})">${wish?'❤️':'🤍'}</button><img class="product-img" src="${p.image}" alt="${p.name}" loading="lazy" onerror="${imgErr}"><div class="product-top"><div><h3>${p.name}</h3><div class="desc">${p.description}</div></div><span class="rating">⭐ ${p.rating}</span></div><div class="nutrition">${p.nutrition?`<span>${p.nutrition.cal} cal</span><span>${p.nutrition.protein}g protein</span><span>${p.nutrition.sugar}g sugar</span>`:'<span>Non-food item</span>'}</div><div class="price-row"><span class="price">${money(p.price)}</span><span class="stock">${stock>0?stock+' left':'Out of stock'}</span></div>${q?`<div class="qty-inline"><button onclick="updateCartQuantity(${p.id},-1)">−</button><strong>${q}</strong><button onclick="updateCartQuantity(${p.id},1)">+</button></div>`:`<div class="card-actions"><button class="details-btn" onclick="openProduct(${p.id})">View</button><button class="add-btn" onclick="addToCart(${p.id})" ${stock<=0?'disabled':''}>${stock<=0?'Out':'Add'}</button></div>`}</article>`}
function renderSuggestions(){const box=qs('#searchSuggestions');if(searchTerm.length<1){box.innerHTML='';return}const hits=products.filter(p=>p.name.toLowerCase().includes(searchTerm.toLowerCase())).slice(0,6);box.innerHTML=hits.map(p=>`<button onclick="selectSuggestion('${p.name.replace(/'/g,"\\'")}')">${p.name} <small>• ${p.category}</small></button>`).join('')}
function selectSuggestion(v){qs('#searchInput').value=v;searchTerm=v;qs('#searchSuggestions').innerHTML='';renderProducts()}
function addToCart(id){const p=product(id),q=cart[id]||0;if(!p)return;if(q>=p.stock){toast('Product out of stock','error');return}cart[id]=q+1;save('apna_cart',cart);renderCart();renderProducts();renderRecommendations();toast(`${p.name} added to cart`)}
function updateCartQuantity(id,change){const p=product(id);if(!p)return;const n=(cart[id]||0)+change;if(n<=0)delete cart[id];else if(n>p.stock){toast('Not enough stock available','warning');return}else cart[id]=n;save('apna_cart',cart);renderCart();renderProducts()}
function removeFromCart(id){delete cart[id];save('apna_cart',cart);renderCart();renderProducts();toast('Item removed','warning')}
function totals(){const subtotal=Object.entries(cart).reduce((s,[id,q])=>s+(product(id)?.price||0)*q,0);let delivery=subtotal===0?0:subtotal>=499?0:35;let discount=subtotal>=699?100:subtotal>=399?50:0;if(coupon==='FIRST50'&&subtotal>=199)discount+=50;if(coupon==='SAVE100'&&subtotal>=799)discount+=100;if(coupon==='WELCOME20')discount+=Math.round(subtotal*.2);if(coupon==='FREESHIP')delivery=0;const wheel=localStorage.getItem(scopedKey('apna_wheel_coupon'));if(wheel)discount+=Number(wheel)||0;return{subtotal,delivery,discount,total:Math.max(0,subtotal+delivery-discount)}}
function renderCart(){const count=Object.values(cart).reduce((a,b)=>a+b,0);qs('#cartCount').textContent=count;const items=Object.entries(cart);qs('#cartItems').innerHTML=items.length?items.map(([id,q])=>{const p=product(id);return `<div class="cart-item"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><div class="small-muted">${q} × ${money(p.price)}</div><div class="qty-inline"><button onclick="updateCartQuantity(${p.id},-1)">−</button><strong>${q}</strong><button onclick="updateCartQuantity(${p.id},1)">+</button></div></div><button class="danger-text" onclick="removeFromCart(${p.id})">Remove</button></div>`}).join(''):`<div class="empty-state"><h3>Cart is empty</h3><p>Add fresh products to continue.</p></div>`;const t=totals();qs('#subtotalValue').textContent=money(t.subtotal);qs('#deliveryValue').textContent=money(t.delivery);qs('#discountValue').textContent='-'+money(t.discount);qs('#finalTotalValue').textContent=money(t.total);qs('#checkoutOpenBtn').disabled=!items.length;renderSmartCart(t.subtotal)}
function renderSmartCart(sub){const goal=499,need=Math.max(0,goal-sub),pct=Math.min(100,sub/goal*100);qs('#smartCart').innerHTML=sub? need?`Add ${money(need)} more for free delivery<div class="progress"><span style="width:${pct}%"></span></div>`:`🎉 Free delivery unlocked!`:''}
function applyCoupon(code){const valid=['FIRST50','SAVE100','WELCOME20','FREESHIP'];if(!valid.includes(code)){toast('Invalid coupon. Try FIRST50, SAVE100, WELCOME20 or FREESHIP','error');return}coupon=code;save('apna_coupon',coupon);qs('#couponInput').value=code;renderCart();toast(`${code} coupon applied`)}
function setAuthMode(mode){
  authMode=mode;
  const isCreate=mode==='create';
  qs('#authTitle').textContent=isCreate?'Create Account':'Login to Account';
  qs('#createAccountTab')?.classList.toggle('active',isCreate);
  qs('#loginAccountTab')?.classList.toggle('active',!isCreate);
  qs('#sendOtpBtn').textContent=isCreate?'Create Account with OTP':'Login with OTP';
  qs('#verifyOtpBtn').textContent=isCreate?'Verify OTP & Create Account':'Verify OTP & Login';
  qs('#loginStepPhone').classList.remove('hidden');
  qs('#loginStepOtp').classList.add('hidden');
  qs('#otpInput').value='';
}
function loginWithOtp(){
  const name=qs('#loginName').value.trim(),phone=cleanPhone(qs('#loginPhone').value.trim()),accounts=readAccounts(),existing=accounts[phone];
  if(!/^[0-9]{10}$/.test(phone)){toast('Enter valid 10 digit phone','error');return}
  if(authMode==='create'){
    if(!name){toast('Enter your full name','error');return}
    if(existing){toast('Account already exists. Use Login tab.','warning');setAuthMode('login');return}
    window.tempUser={name:name.replace(/\s+/g,' ').trim(),phone:'+91 '+phone,createdAt:new Date().toISOString(),coins:0};
  }else{
    if(!existing){toast('No account found. Create account first.','warning');setAuthMode('create');qs('#loginName').focus();return}
    window.tempUser={...existing,lastLogin:new Date().toISOString()};
    qs('#loginName').value=existing.name||'';
  }
  otp=String(Math.floor(1000+Math.random()*9000));
  qs('#demoOtpText').textContent=otp;
  qs('#loginStepPhone').classList.add('hidden');
  qs('#loginStepOtp').classList.remove('hidden');
  qs('#otpInput').focus();
  toast('Demo OTP generated. Use the OTP shown on screen.');
}
function verifyOtp(){
  if(qs('#otpInput').value!==otp){toast('Wrong OTP','error');return}
  const phone=cleanPhone(window.tempUser?.phone),accounts=readAccounts();
  user={...window.tempUser,phone:'+91 '+phone,loggedIn:true,username:window.tempUser.name};
  accounts[phone]={...user,loggedIn:false,lastLogin:new Date().toISOString()};
  writeAccounts(accounts);
  localStorage.setItem('apna_user',JSON.stringify(user));
  refreshState();rerenderAll();closeModal('loginModal');
  toast(`${authMode==='create'?'Account created':'Logged in'}: ${user.name}`);
}
function renderUser(){
  const display=user?(user.name||user.username||'User'):'Guest';
  qs('#userBtn').textContent=user?`👤 ${display}`:'Login / Create';
  const chip=qs('#usernameDisplay');
  if(chip){chip.textContent=user?`👋 Hi, ${display}`:'👋 Guest';chip.classList.toggle('hidden',!user)}
}
function showProfile(){openModal('successModal');qs('#successContent').innerHTML=`<button class="close-btn modal-close" onclick="closeModal('successModal')">×</button><h2>👤 ${user.name}</h2><p>${user.phone}</p><p><strong>Username:</strong> ${user.username||user.name}</p><p><strong>Apna Coins:</strong> ${user.coins||0}</p><button class="danger-text" onclick="logout()">Logout</button>`}
function logout(){localStorage.removeItem('apna_user');user=null;refreshState();rerenderAll();closeAll();toast('Logged out')}
function checkout(){if(!Object.keys(cart).length){toast('Cart is empty','error');return}if(!user){toast('Login required before checkout','warning');openModal('loginModal');return}qs('#customerName').value=user.name||'';qs('#customerPhone').value=(user.phone||'').replace(/\D/g,'').slice(-10);renderOrderPreview();openModal('checkoutModal')}
function renderOrderPreview(){const t=totals();qs('#orderPreview').innerHTML=`<h3>Order Summary</h3>${Object.entries(cart).map(([id,q])=>`<p>${product(id).name} × ${q} <strong>${money(product(id).price*q)}</strong></p>`).join('')}<hr><p>Delivery: ${money(t.delivery)} | Discount: ${money(t.discount)}</p><h3>Total: ${money(t.total)}</h3>`}
function placeOrder(e){e.preventDefault();const name=qs('#customerName').value.trim(),phone=qs('#customerPhone').value.trim(),addr=qs('#customerAddress').value.trim(),pay=qs('#paymentMethod').value;if(!name||!/^[0-9]{10}$/.test(phone)||addr.length<8||!pay){toast('Please fill valid checkout details','error');return}const t=totals(),id='APNA'+Date.now().toString().slice(-7),partner=partners[Math.floor(Math.random()*partners.length)],items=Object.entries(cart).map(([pid,q])=>({id:Number(pid),name:product(pid).name,qty:q,price:product(pid).price}));const order={id,date:new Date().toISOString(),items,total:t.total,subtotal:t.subtotal,delivery:t.delivery,discount:t.discount,paymentMethod:pay,status:'Order confirmed',address:addr,customer:name,phone,partner};orders.unshift(order);save('apna_orders',orders);user.coins=(user.coins||0)+Math.floor(t.total/20);localStorage.setItem('apna_user',JSON.stringify(user));const accounts=readAccounts(),ph=cleanPhone(user.phone);accounts[ph]={...user,loggedIn:false};writeAccounts(accounts);cart={};save('apna_cart',cart);localStorage.removeItem(scopedKey('apna_coupon'));localStorage.removeItem(scopedKey('apna_wheel_coupon'));coupon='';renderCart();renderProducts();renderOrderHistory();renderDashboard();renderUser();closeModal('checkoutModal');showSuccess(order);startDeliveryTracking(order,true);addNotification(`Order ${id} confirmed. ${partner.name} assigned.`)}
function showSuccess(order){openModal('successModal');qs('#successContent').innerHTML=`<h2>✅ Order Placed!</h2><h3>${order.id}</h3><p>Total ${money(order.total)} • ${order.paymentMethod}</p><div class="order-preview"><h3>Delivery Partner</h3><p>${order.partner.photo} <strong>${order.partner.name}</strong></p><p>${order.partner.phone} • ${order.partner.vehicle} • ⭐ ${order.partner.rating}</p><p>Estimated delivery: 12–25 minutes</p></div><button class="primary-btn full" onclick="closeModal('successModal');document.getElementById('trackingSection').scrollIntoView({behavior:'smooth'})">Track order</button>`}
function startDeliveryTracking(order,fresh=false){tracking=order;save('apna_tracking',order);showTracking(order);const steps=['Order confirmed','Packed','Out for delivery','Delivered'];let i=steps.indexOf(order.status);if(i<0)i=0;function tick(){if(i>=steps.length)return;tracking.status=steps[i];save('apna_tracking',tracking);showTracking(tracking);orders=orders.map(o=>o.id===tracking.id?{...o,status:tracking.status}:o);save('apna_orders',orders);if(fresh&&i>0)addNotification(`${tracking.id}: ${tracking.status}`);i++;if(i<steps.length)setTimeout(tick,3500)}tick()}
function showTracking(order){
  qs('#trackingSection').classList.remove('hidden');
  qs('#trackingOrderId').textContent=`${order.id} • ${order.status}`;
  qs('#partnerCard').innerHTML=`<p>${order.partner.photo} <strong>${order.partner.name}</strong></p><p>${order.partner.phone}</p><p>${order.partner.vehicle} • ⭐ ${order.partner.rating}</p><p><strong>ETA:</strong> ${order.status==='Delivered'?'Delivered':'12–25 mins'}</p><button class="secondary-btn full" onclick="detectLocation()" style="margin-top:10px">📍 Update live location</button>`;
  const steps=['Order confirmed','Packed','Out for delivery','Delivered'];
  qs('#statusTimeline').innerHTML=steps.map(s=>`<div class="timeline-step ${steps.indexOf(s)<=steps.indexOf(order.status)?'active':''}"><span class="timeline-dot"></span><div>${s}</div></div>`).join('');
  const customer=order.customerLocation||readUserLocation()||{lat:23.2599,lng:77.4126,label:'Customer'};
  const store=order.storeLocation||makeStoreNear(customer);
  order.customerLocation=customer;order.storeLocation=store;
  const pct=Math.max(0,steps.indexOf(order.status))/(steps.length-1);
  const rider=interpolate(store,customer,pct||0);
  initRealMap(customer,store,rider,order.status);
}
function renderOrderHistory(){qs('#ordersContent').innerHTML=orders.length?orders.map(o=>`<div class="order-card"><h3>${o.id}</h3><p>${new Date(o.date).toLocaleString('en-IN')} • ${o.paymentMethod}</p><p>${o.items.map(i=>`${i.name} × ${i.qty}`).join(', ')}</p><p><strong>${money(o.total)}</strong> • ${o.status}</p><button class="secondary-btn" onclick="viewOrder('${o.id}')">View summary</button> <button class="secondary-btn" onclick="reorder('${o.id}')">Buy Again</button></div>`).join(''):`<div class="empty-state"><h3>No orders yet</h3><p>Your order history will appear here.</p></div>`}
function viewOrder(id){const o=orders.find(x=>x.id===id);openModal('successModal');qs('#successContent').innerHTML=`<button class="close-btn modal-close" onclick="closeModal('successModal')">×</button><h2>${o.id}</h2><p>${new Date(o.date).toLocaleString('en-IN')}</p><p>${o.items.map(i=>`${i.name} × ${i.qty}`).join('<br>')}</p><h3>${money(o.total)}</h3><p>${o.paymentMethod} • ${o.status}</p><p>${o.address}</p>`}
function reorder(id){const o=orders.find(x=>x.id===id);if(!o)return;o.items.forEach(i=>{cart[i.id]=(cart[i.id]||0)+i.qty});save('apna_cart',cart);renderCart();renderProducts();toast('Items added again')}
function buyAgain(){if(!orders.length){toast('No past order to buy again','warning');return}reorder(orders[0].id)}
function renderWishlist(){const list=products.filter(p=>wishlist.includes(p.id));qs('#wishlistContent').innerHTML=list.length?list.map(p=>`<div class="order-card"><h3>${p.name}</h3><p>${p.category} • ⭐ ${p.rating} • ${money(p.price)}</p><button class="primary-btn" onclick="addToCart(${p.id})">Add to cart</button> <button class="danger-text" onclick="toggleWishlist(${p.id});renderWishlist()">Remove</button></div>`).join(''):`<div class="empty-state"><h3>No wishlist items</h3><p>Tap heart on products to save favorites.</p></div>`}
function toggleWishlist(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save('apna_wishlist',wishlist);qs('#wishlistCount').textContent=wishlist.length;renderProducts();toast(wishlist.includes(id)?'Added to wishlist':'Removed from wishlist')}
function renderNotifications(){qs('#notificationCount').textContent=notifications.length;qs('#notificationsContent').innerHTML=notifications.length?notifications.map(n=>`<div class="notify-card"><strong>${n.text}</strong><p>${new Date(n.date).toLocaleString('en-IN')}</p></div>`).join(''):`<div class="empty-state"><h3>No notifications</h3><p>Order and offer updates appear here.</p></div>`}
function openProduct(id){const p=product(id);save('apna_recent',[id,...readScoped('apna_recent','[]').filter(x=>x!==id)].slice(0,8));openModal('productModal');qs('#productModalContent').innerHTML=`<button class="close-btn modal-close" onclick="closeModal('productModal')">×</button><div class="detail-grid"><img src="${p.image}" alt="${p.name}" loading="lazy" onerror="${imgErr}"><div><span class="eyebrow">${p.category}</span><h2>${p.name}</h2><p>${p.description}</p><h3>${money(p.price)}</h3><p>⭐ ${p.rating} • Stock ${p.stock-(cart[p.id]||0)}</p><div class="nutrition">${p.nutrition?Object.entries(p.nutrition).map(([k,v])=>`<span>${k}: ${v}</span>`).join(''):'<span>Household / personal care product</span>'}</div><button class="primary-btn full" onclick="addToCart(${p.id});closeModal('productModal')">Add to cart</button><button class="secondary-btn full" style="margin-top:10px" onclick="toggleWishlist(${p.id})">Save to wishlist</button></div></div>`;renderRecommendations()}
function renderRecommendations(){let ids=[...new Set([...Object.keys(cart).map(Number),...readScoped('apna_recent','[]')])];let cats=ids.map(id=>product(id)?.category).filter(Boolean);let rec=products.filter(p=>cats.includes(p.category)&&!cart[p.id]).slice(0,8);if(rec.length<4)rec=products.filter(p=>p.featured).slice(0,8);qs('#recommendations').innerHTML=rec.map(p=>`<button class="kit-card" onclick="openProduct(${p.id})"><span><img src="${p.image}" style="width:56px;height:56px;border-radius:14px;object-fit:cover"></span><strong>${p.name}</strong><small>${money(p.price)}</small></button>`).join('')}
function addKit(type){const kits={breakfast:[13,19,16,2],chai:[13,35,22,16],party:[25,32,31,28],cleaning:[37,38,39,41]};(kits[type]||[]).forEach(addToCart);toast('Quick kit added')}
function assistantSuggest(){const q=qs('#assistantInput').value.toLowerCase();let list=products;if(q.includes('breakfast'))list=products.filter(p=>['Dairy','Bakery','Fruits'].includes(p.category));else if(q.includes('clean'))list=products.filter(p=>p.category==='Household');else if(q.includes('snack')||q.includes('party'))list=products.filter(p=>['Snacks','Beverages'].includes(p.category));const budget=(q.match(/under\s*(\d+)/)||[])[1];if(budget)list=list.filter(p=>p.price<=Number(budget));qs('#assistantResults').innerHTML=list.slice(0,6).map(p=>`<button class="kit-card" onclick="addToCart(${p.id})"><strong>${p.name}</strong><small>${money(p.price)} • Add</small></button>`).join('')||'<p>No suggestion found.</p>'}
function renderDashboard(){const total=orders.reduce((s,o)=>s+o.total,0),count=orders.length,items={};orders.forEach(o=>o.items.forEach(i=>items[i.name]=(items[i.name]||0)+i.qty));const top=Object.entries(items).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Nothing yet';qs('#dashboardGrid').innerHTML=`<div><strong>${money(total)}</strong><span>Total spent</span></div><div><strong>${count}</strong><span>Orders</span></div><div><strong>${top}</strong><span>Most purchased</span></div><div><strong>${user?.coins||0}</strong><span>Apna Coins</span></div>`}

let apnaMap=null,apnaRoute=null,apnaMarkers={};
function saveUserLocation(loc){localStorage.setItem('apna_user_location',JSON.stringify(loc))}
function readUserLocation(){try{return JSON.parse(localStorage.getItem('apna_user_location')||'null')}catch(e){return null}}
function makeStoreNear(customer){return {lat:customer.lat+0.012,lng:customer.lng-0.014,label:'Apna Mart Store'}}
function interpolate(a,b,t){return {lat:a.lat+(b.lat-a.lat)*t,lng:a.lng+(b.lng-a.lng)*t,label:'Delivery Partner'}}
function mapIcon(html){return L.divIcon({html:`<div class="leaflet-emoji-marker">${html}</div>`,className:'',iconSize:[38,38],iconAnchor:[19,19]})}
function initRealMap(customer,store,rider,status='Tracking'){
  const mapEl=qs('#realMap');if(!mapEl)return;
  if(typeof L==='undefined'){qs('#mapStatusCard').textContent='Map library not loaded. Check internet connection.';return}
  store=store||makeStoreNear(customer);rider=rider||store;
  if(!apnaMap){
    apnaMap=L.map('realMap',{zoomControl:true,attributionControl:true});
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(apnaMap);
  }
  setTimeout(()=>apnaMap.invalidateSize(),120);
  Object.values(apnaMarkers).forEach(m=>m.remove());apnaMarkers={};
  if(apnaRoute){apnaRoute.remove();apnaRoute=null}
  apnaMarkers.store=L.marker([store.lat,store.lng],{icon:mapIcon('🏪')}).addTo(apnaMap).bindPopup('Apna Mart Store');
  apnaMarkers.customer=L.marker([customer.lat,customer.lng],{icon:mapIcon('🏠')}).addTo(apnaMap).bindPopup(customer.label||'Your location');
  apnaMarkers.rider=L.marker([rider.lat,rider.lng],{icon:mapIcon('🏍️')}).addTo(apnaMap).bindPopup('Delivery Partner');
  apnaRoute=L.polyline([[store.lat,store.lng],[rider.lat,rider.lng],[customer.lat,customer.lng]],{weight:5,opacity:.85,dashArray:'8 8'}).addTo(apnaMap);
  apnaMap.fitBounds(apnaRoute.getBounds(),{padding:[45,45],maxZoom:16});
  const km=distanceKm(rider,customer),eta=status==='Delivered'?'Delivered':Math.max(2,Math.round(km/0.35))+' min';
  qs('#mapStatusCard').textContent=`${status} • Rider ${km.toFixed(1)} km away • ETA ${eta}`;
}
function distanceKm(a,b){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,lat1=a.lat*Math.PI/180,lat2=b.lat*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}

function detectLocation(){
  const set=t=>{qs('#locationText').textContent=t;toast('Location updated')};
  const fallback={lat:23.2599,lng:77.4126,label:'Bhopal, MP'};
  if(!navigator.geolocation){set('Bhopal, MP • 12 min');saveUserLocation(fallback);return}
  navigator.geolocation.getCurrentPosition(pos=>{
    const loc={lat:pos.coords.latitude,lng:pos.coords.longitude,label:'Current location'};
    saveUserLocation(loc);set('Current location • live map');
    if(tracking){tracking.customerLocation=loc;save('apna_tracking',tracking);showTracking(tracking)}else initRealMap(loc,null,null);
  },()=>{set('Bhopal, MP • 12 min');saveUserLocation(fallback);if(tracking)showTracking(tracking);else initRealMap(fallback,null,null)}, {enableHighAccuracy:true,timeout:9000,maximumAge:60000});
}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('apna_dark',document.body.classList.contains('dark'));qs('#themeBtn').textContent=document.body.classList.contains('dark')?'☀️':'🌙'}
function spinWheel(){const today=new Date().toDateString();if(localStorage.getItem(scopedKey('apna_spin_day'))===today){toast('You already used today’s spin','warning');return}const prizes=[10,25,0,50,75,100],idx=Math.floor(Math.random()*prizes.length),prize=prizes[idx];spinRotation+=1800+idx*60+Math.random()*40;qs('#wheel').style.transform=`rotate(${spinRotation}deg)`;qs('#spinBtn').disabled=true;setTimeout(()=>{save('apna_spin_day',today);if(prize){save('apna_wheel_coupon',prize);toast(`You won ${money(prize)} discount`)}else{coupon='FREESHIP';save('apna_coupon',coupon);toast('You won free delivery')}renderCart();qs('#spinBtn').disabled=false;closeModal('spinModal')},4200)}
function startHero(){const dots=qs('#heroDots');dots.innerHTML=heroSlides.map((_,i)=>`<button class="${i?'':'active'}" onclick="setHero(${i})"></button>`).join('');setInterval(()=>setHero((heroIndex+1)%heroSlides.length),4500)}function setHero(i){heroIndex=i;qs('#heroTitle').textContent=heroSlides[i][0];qs('#heroSubtitle').textContent=heroSlides[i][1];qs('#heroVisual').textContent=heroSlides[i][2];qsa('#heroDots button').forEach((b,j)=>b.classList.toggle('active',i===j))}
function startFlashTimer(){function tick(){const now=new Date(),end=new Date();end.setHours(23,59,59,999);let s=Math.max(0,Math.floor((end-now)/1000)),h=String(Math.floor(s/3600)).padStart(2,'0');s%=3600;let m=String(Math.floor(s/60)).padStart(2,'0'),sec=String(s%60).padStart(2,'0');qs('#flashTimer').textContent=`${h}:${m}:${sec}`}tick();setInterval(tick,1000)}
window.addToCart=addToCart;window.updateCartQuantity=updateCartQuantity;window.removeFromCart=removeFromCart;window.toggleWishlist=toggleWishlist;window.openProduct=openProduct;window.selectSuggestion=selectSuggestion;window.closeModal=closeModal;window.viewOrder=viewOrder;window.reorder=reorder;document.addEventListener('DOMContentLoaded',init);
